### PR TITLE
Added README.md file

### PR DESCRIPTION
**Pull request by Ayush9026**
## Description

This PR solves issue https://github.com/in-toto/in-toto.io/issues/27 . A comprehensive README.md file will help new contributors and users understand the purpose and functionality of the project.

### CODE REVIEW

**Comment by Ayush9026** [comment]
Thank you, @lukpueh sir, for your feedback. I agree that project-wide documentation should be on in-toto.io to avoid duplication. I'll update the README.md to focus on the repo's purpose and contribution guidelines.

Can I raise a PR to integrate the comprehensive project information into the in-toto.io site?

Thanks again for your input!

**Comment by DarikshaAnsari** [comment]
@lukpueh, I noticed that the new in-toto/in-toto.io/readme.md file added by @Ayush9026 contains content similar to what's already in the [in-toto/community/readme.md](https://github.com/in-toto/community/blob/main/README.md) file. To avoid any redundancy, it might be helpful to review and ensure consistency between the two documents.

**Comment by Ayush9026** [comment]
Hi @DarikshaAnsari ,

Thank you for pointing that out. Please wait for @lukpueh sir review and feedback to ensure everything is aligned correctly.

As @lukpueh suggested, I will focus the new README on the purpose of the repo and contribution guidelines, while integrating the comprehensive project information into the in-toto.io site. They will review it.

I'll raise a PR for any changes required to maintain consistency between the two documents.

Thanks for your feedback!

Best regards,  
Ayush9026

**Comment by lukpueh** [comment]
> In my opinion, the README should mostly describe the purpose of this repo (i.e. Hugo sources for in-toto.io project website) and how to contribute.

☝️

**Comment by lukpueh** [comment]
Closing stale pr...

**Pull request closed without merging**
